mxnet_variant_str:
  #  - gpu_openblas
  #  - gpu_mkl
  #  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
  - invalid                    # [win]
mxnet_variant_version:
  #  - 0.0.50
  #  - 0.0.50
  #  - 0.0.50                     # [x86 or x86_64]
  - 0.0.50                     # [not win]
  - invalid                    # [win]
mxnet_blas_impl:
  #  - openblas
  #  - mkl
  #  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
  - invalid                    # [win]

zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
  - mxnet_blas_impl


# Use gcc 8 for ppc64le
c_compiler_version:            # [ppc64le]
  - 8                          # [ppc64le]
cxx_compiler_version:          # [ppc64le]
  - 8                          # [ppc64le]


# Default osx-64 sdk does not support c++14 adequately.
CONDA_BUILD_SYSROOT:           # [osx and x86_64]
  - /opt/MacOSX10.12.sdk       # [osx and x86_64]
