mxnet_variant_str:
  #  - gpu_openblas
  #  - gpu_mkl
  #  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
mxnet_variant_version:
  #  - 0.0.50
  #  - 0.0.50
  #  - 0.0.50                     # [x86 or x86_64]
  - 0.0.50                     # [not win]
mxnet_blas_impl:
  #  - openblas
  #  - mkl
  #  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]

zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
  - mxnet_blas_impl
