mxnet_variant_str:
  #  - gpu_openblas
  #  - gpu_mkl
  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
mxnet_variant_version:
  #  - 0.0.10
  #  - 0.0.20
  - 0.0.30         # [x86 or x86_64]
  - 0.0.40         # [not win]
mxnet_blas_impl:
  #  - openblas
  #  - mkl
  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
python:
  - 3.7
  - 3.8
  - 3.9
  - 3.10
mxnet_version:
  - 1.5.0
c_compiler:
  - gcc                        # [linux and aarch64]
  - clang                      # [osx]
  - vs2017                     # [win]
cxx_compiler:
  - gxx                        # [linux and aarch64]
  - clangxx                    # [osx]
  - vs2017                     # [win]
vc:  # [win]
  - 14  # [win]
c_compiler_version:        # [linux or osx]
  - 7.5.0                  # [linux and not (s390x or aarch64 or ppc64le)]
  - 7.3.0                  # [linux and ppc64le]
  - 7.5.0                  # [linux and s390x]
  - 10.2.0                 # [linux and aarch64]
  - 10                     # [osx and x86_64]
  - 12                     # [osx and arm64]
cxx_compiler_version:      # [linux or osx]
  - 7.5.0                  # [linux and not (s390x or aarch64 or ppc64le)]
  - 7.3.0                  # [linux and ppc64le]
  - 7.5.0                  # [linux and s390x]
  - 10.2.0                 # [linux and aarch64]
  - 10                     # [osx and x86_64]
  - 12                     # [osx and arm64]
fortran_compiler_version:  # [linux]
  - 7.5.0                  # [linux and not (s390x or aarch64 or ppc64le)]
  - 7.3.0                  # [linux and ppc64le]
  - 7.5.0                  # [linux and s390x]
  - 10.2.0                 # [linux and aarch64]
#cudatoolkit_version:
#  - 8.0
#  - 9.0
#
#cudnn_version:
#  - 7
libopencv:  # [win]
  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
  - mxnet_blas_impl
