mxnet_variant_str:
  #  - gpu_openblas
  #  - gpu_mkl
  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
mxnet_variant_version:
  #  - 0.0.10
  #  - 0.0.20
  - 0.0.30         # [x86 or x86_64]
  - 0.0.40         # [not win]
mxnet_blas_impl:
  #  - openblas
  #  - mkl
  - mkl                        # [x86 or x86_64]
  - openblas                   # [not win]
mxnet_version:
  - 1.5.0
#cudatoolkit_version:
#  - 8.0
#  - 9.0
#
#cudnn_version:
#  - 7
libopencv:  # [win]
  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
  - mxnet_blas_impl
