mxnet_variant_str:
  #  - gpu_openblas
  #  - gpu_mkl
  - mkl
  - openblas
mxnet_variant_version:
  #  - 0.0.10
  #  - 0.0.20
  - 0.0.30
  - 0.0.40
mxnet_blas_impl:
  #  - openblas
  #  - mkl
  - mkl
  - openblas
mxnet_version:
  - 1.5.0
openblas:
  - 0.3.20
#cudatoolkit_version:
#  - 8.0
#  - 9.0
#
#cudnn_version:
#  - 7
#libopencv:  # [win]
#  - 3.4.1   # [win]
zip_keys:
  - mxnet_variant_str
  - mxnet_variant_version
  - mxnet_blas_impl
