{% set build_number = "0" %}

package:
  name: mxnet-gpu
  version: {{ mxnet_version }}

requirements:
  run:
    - mxnet {{ mxnet_version }}
    - _mutex_mxnet {{ mxnet_variant_version }} {{ mxnet_variant_str }}
