{% set build_number = "0" %}

package:
  name: mxnet
  version: {{ mxnet_version }}

build:
  number: {{ build_number }}

requirements:
  run:
    - libmxnet {{ mxnet_version }}
    - py-mxnet {{ mxnet_version }}

about:
  summary: MXNet metapackage for installing lib,py-MXNet Conda packages

extra:
  recipe-maintainers:
    - nehaljwani
